// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7EUI_qk0ZGLMxOQlH-habu9u0T6L69WY',
    appId: '1:765571825739:web:432751bcd426ff7d794dce',
    messagingSenderId: '765571825739',
    projectId: 'dog-health-32e61',
    authDomain: 'dog-health-32e61.firebaseapp.com',
    storageBucket: 'dog-health-32e61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClLhpvpkWOvqQik9CZOkVNJzKo8hMnTWA',
    appId: '1:765571825739:android:83135d53fae20690794dce',
    messagingSenderId: '765571825739',
    projectId: 'dog-health-32e61',
    storageBucket: 'dog-health-32e61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0RF2r1kaqOAr0y9xBh2gS3VmoltmecH8',
    appId: '1:765571825739:ios:4ab448e05d8d002c794dce',
    messagingSenderId: '765571825739',
    projectId: 'dog-health-32e61',
    storageBucket: 'dog-health-32e61.appspot.com',
    iosClientId: '765571825739-o830sv7p6rve92hnk1jn160a4bjoihg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogHealth',
  );
}
